### ISSUE TITLE
litespeed error get request

### ISSUE THREAD

**Issue by gettohub** [sahilchaddha/rudyjs#3]
litespeed server getting this error when i try to get method. how i can use get method for litespeed?

`ERROR ::: Attack_Service ::: 404 :: Error Occured attackId : 496 ***
{ code: 404,
  err:
   { Error: read ECONNRESET
       at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } }
*** INFO ::: Attack_Service ::: Request Succeeded. RUDY attack failed attackId : 478 ***
{ status: 400,
  message:
   '<html>\n<head><title> 400 Bad Request\r\n</title></head>\n<body><h1> 400 Bad Request\r\n</h1>\nIt is not a valid request!<hr />\nPowered By <a href=\'http://www.litespeedtech.com\'>LiteSpeed Web Server</a><br />\n<font face="Verdana, Arial, Helvetica" size=-1>LiteSpeed Technologies is not responsible for administration and contents of this web site!</font></body></html>\n' }`

**Comment by sahilchaddha** [comment]
The request is not valid. Litespeed returned in error `It is not a valid request!`
